fixup! pbt: convert gpb-eqc to PropEr & add to test suite
Restore rebar2 compat for basic eunit tests

With rebar2 we don't have the possibility to run proper, but at least
compiling and running eunit tests no longer fails. Previously, since
proper was not available, since old rebar2 does not know about profiles,
"rebar eunit" failed as indicated below (abridged for readability).

    % rebar -v eunit
    ==> gpb (eunit)
    INFO:  sh info:
            cwd: "/path/to/gpb"
            cmd: cp -R src/gpb_gen_decoders.erl [...] ".eunit"
    WARN:  Failed to restore /path/to/gpb/.rebar/erlcinfo file. Discarding it.
    Compiled src/gpb_codegen.erl
    [...]
    Compiled src/gpb_gen_nif.erl
    test/prop_gpb.erl:9: can't find include lib "proper/include/proper.hrl"
    test/prop_gpb.erl:334: undefined macro 'SUCHTHAT/3'
    test/prop_gpb.erl:359: undefined macro 'FORALL/3'
    [...]
    Compiling test/prop_gpb.erl failed:
    ERROR: eunit failed while processing /path/to/gpb: rebar_abort